# This is just to avoid the default Ruby environment. 
# Project is not actually PHP, of course.
language: php

php:
  # using major version aliases

  # aliased to a recent 5.4.x version
  - 5.4

before_script: 
  - echo "Changing directory to 'tests'"
  - cd ./tests
  - pwd

# Run the Jasmine tests
script: ./run.sh