# This is just to avoid the default Ruby environment. 
# Project is not actually PHP, of course.
#language: php
language: python

before_script: 
  - echo "Changing directory to 'tests'"
  - cd ./tests
  - pwd
#  - bundle exec rackup &
  - python -m SimpleHTTPServer 3000 &
  - sleep 5 # give Web server some time to bind to sockets, etc

# Run the Jasmine tests
#script: ./run.sh

script: phantomjs run-jasmine.js http://localhost:3000/SpecRunner.html
