# This is just to avoid the default Ruby environment. 
# Project is not actually PHP, of course.
#language: php
language: python

php:
  # using major version aliases

  # aliased to a recent 5.4.x version
  - 5.4

before_script: 
  - echo "Changing directory to 'tests'"
  - cd ./tests
  - pwd
  - python -m SimpleHTTPServer 3000 & 

# Run the Jasmine tests
#script: ./run.sh

script: phantomjs run-jasmine.js http://localhost:3000/SpecRunner.html